# Generated by Django 5.2 on 2025-05-01 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especializacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsableSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioInscrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.PositiveIntegerField()),
                ('ubicacion', models.CharField(max_length=100)),
                ('responsable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_bbdd.responsablesala')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('horario', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('duracion', models.PositiveIntegerField(help_text='Duración en minutos')),
                ('plazas_disponibles', models.PositiveIntegerField()),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='app_bbdd.monitor')),
                ('sala_principal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_principales', to='app_bbdd.sala')),
                ('salas_secundarias', models.ManyToManyField(blank=True, related_name='actividades_secundarias', to='app_bbdd.sala')),
                ('usuarios', models.ManyToManyField(related_name='actividades', to='app_bbdd.usuarioinscrito')),
            ],
        ),
    ]
