# Generated by Django 5.2 on 2025-05-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bbdd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='actividades', to='app_bbdd.usuarioinscrito'),
        ),
    ]
