# Generated by Django 5.2 on 2025-05-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bbdd', '0002_alter_actividad_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
